#pragma once

typedef enum {
    STATUS_SUCCESS = 0,
    STATUS_INIT_ERROR,
    STATUS_NULL_POINTER_ERROR,
    STATUS_MEMORY_ALLOCATION_ERROR,
    STATUS_STACK_UNDERFLOW_ERROR,
    STATUS_OBJECT_S_NULL_ERROR,
    STATUS_FREE_ERROR,
    STATUS_INIT_CALLBACK_ERROR,
    STATUS_MEMCPY_ERROR,
    STATUS_COPY_CALLBACK_ERROR,
} Status;